<div class="filter-done">
    <p class="filter-label"><?php /* @escapeNotVerified */ echo __('Filter Products') ?></p>
    <button type="button" class="js-facets-done done-button action primary">
        <?php /* @escapeNotVerified */ echo __('Done') ?>
    </button>
</div>
<script type="text/x-magento-init">
{
    "#narrow-by-list": {
        "multiFacetNavigation": {
            "linkSelector": ".js-facet-link",
            "isMobileMediaQuery": "(max-width: 768px)",
            "closeNavigationSelector": false
        }
    }
}
</script>
